export const SET_HE_THONG_RAP_CHIEU = "SET_HE_THONG_RAP_CHIEU";
export const SET_CHI_TIET_PHIM = "SET_CHI_TIET_PHIM";
export const SET_THONG_TIN_RAP = "SET_THONG_TIN_RAP";
export const SET_THONG_TIN_CUM_RAP = "SET_THONG_TIN_CUM_RAP";
export const SET_THONG_TIN_CUM_RAP_CHI_TIET=" SET_THONG_TIN_CUM_RAP_CHI_TIET"
